/*

//This is an array of the rankings which is used by the Team object to find a ranking of a team.
int rankarray12 [][19] = {{0, 23, 20, 14, 5, 5, 9, 11, 14, 16, 20, 22, 25, 25, 27, 29, 27, 26, 27},
{0, 10, 6, 3, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 5, 5, 2, 2},
{0, 6, 3, 6, 3, 3, 4, 4, 6, 7, 7, 5, 5, 4, 6, 8, 11, 10, 10},
{0, 19, 24, 22, 19, 21, 27, 25, 27, 28, 28, 27, 24, 24, 23, 24, 25, 25, 23},
{0, 22, 23, 19, 23, 24, 26, 28, 29, 30, 29, 29, 29, 28, 28, 26, 23, 20, 18},
{0, 9, 8, 12, 11, 9, 6, 6, 5, 5, 3, 3, 6, 6, 8, 11, 14, 13, 13},
{0, 16, 18, 16, 15, 12, 15, 21, 22, 22, 23, 19, 17, 11, 11, 14, 13, 11, 11},
{0, 31, 31, 32, 32, 32, 32, 30, 30, 29, 30, 30, 30, 27, 24, 20, 22, 24, 24},
{0, 14, 10, 15, 12, 15, 13, 18, 15, 14, 18, 15, 16, 19, 16, 13, 10, 14, 15},
{0, 13, 9, 10, 14, 13, 17, 12, 12, 9, 8, 7, 7, 7, 5, 2, 2, 1, 1},
{0, 12, 13, 13, 18, 20, 20, 19, 19, 17, 14, 17, 19, 20, 21, 25, 28, 28, 28},
{0, 1, 5, 4, 7, 8, 12, 8, 7, 6, 6, 6, 4, 9, 7, 6, 6, 4, 6},
{0, 5, 4, 2, 1, 1, 1, 2, 3, 3, 2, 1, 1, 1, 1, 3, 3, 7, 9},
{0, 32, 32, 27, 31, 31, 22, 26, 23, 15, 11, 11, 15, 10, 9, 9, 9, 8, 7},
{0, 29, 29, 31, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 32, 31, 31, 31, 31},
{0, 17, 19, 28, 26, 27, 30, 32, 32, 32, 32, 32, 32, 32, 31, 32, 32, 32, 32},
{0, 27, 30, 25, 29, 26, 19, 17, 16, 12, 15, 18, 20, 18, 20, 21, 19, 19, 20},
{0, 30, 28, 29, 21, 14, 8, 10, 9, 11, 16, 14, 14, 16, 17, 16, 15, 12, 12},
{0, 2, 1, 5, 8, 6, 5, 7, 8, 8, 9, 8, 8, 5, 3, 1, 4, 5, 4},
{0, 11, 16, 24, 28, 28, 24, 24, 20, 26, 22, 16, 13, 15, 18, 22, 18, 17, 19},
{0, 3, 7, 8, 6, 10, 7, 3, 2, 2, 5, 10, 9, 8, 10, 7, 12, 15, 14},
{0, 21, 17, 18, 17, 23, 25, 23, 24, 25, 25, 26, 22, 23, 22, 19, 21, 23, 25},
{0, 26, 25, 30, 27, 29, 29, 29, 28, 24, 26, 28, 28, 29, 29, 30, 30, 30, 30},
{0, 7, 12, 7, 9, 7, 11, 13, 13, 18, 21, 24, 27, 30, 30, 27, 29, 29, 29},
{0, 8, 11, 9, 16, 16, 10, 14, 10, 10, 10, 9, 11, 14, 13, 15, 16, 18, 17},
{0, 28, 27, 23, 25, 19, 18, 20, 21, 23, 24, 23, 26, 21, 19, 17, 17, 16, 16},
{0, 15, 14, 11, 13, 11, 14, 16, 17, 20, 17, 20, 21, 22, 25, 23, 24, 21, 22},
{0, 4, 2, 1, 4, 4, 3, 5, 4, 4, 4, 4, 3, 3, 4, 4, 1, 3, 3},
{0, 20, 26, 17, 10, 17, 16, 9, 11, 13, 12, 12, 12, 13, 12, 10, 7, 6, 5},
{0, 25, 21, 21, 20, 22, 23, 22, 26, 21, 13, 13, 10, 12, 15, 18, 20, 22, 21},
{0, 18, 22, 26, 24, 25, 28, 27, 25, 27, 27, 25, 23, 26, 26, 28, 26, 27, 26},
{0, 24, 15, 20, 22, 18, 21, 15, 18, 19, 19, 21, 18, 17, 14, 12, 8, 9, 8}};

//This is an array of booleans which is used to determine whether a team is playing at home during a given week.
bool homearray12 [][18] = {{false, true, false, true, true, false, true, false, true, false, true, false, true, false, false, true, true, false},
{false, false, true, false, true, false, true, true, false, true, false, true, false, true, false, true, false, true},
{false, true, false, true, true, false, true, false, true, false, true, false, false, true, false, true, true, false},
{false, false, true, false, true, false, false, true, true, false, false, true, false, true, true, true, false, true},
{false, false, true, true, false, true, true, true, false, false, true, true, false, false, true, false, true, false},
{false, true, false, true, false, false, true, true, true, false, true, false, true, true, false, true, false, false},
{false, false, true, false, false, true, false, true, true, true, true, false, true, false, true, false, false, true},
{false, true, false, true, false, false, false, false, true, true, true, false, true, false, true, true, false, false},
{false, false, false, true, true, true, true, false, true, false, false, true, true, true, false, true, true, false},
{false, true, false, true, true, false, false, true, true, false, false, true, false, true, false, false, true, true},
{false, true, false, false, true, true, false, false, true, false, false, true, true, true, false, false, true, true},
{false, true, true, false, true, false, false, false, true, true, true, false, false, true, true, false, true, false},
{false, true, false, false, true, false, true, true, true, true, false, true, false, false, false, true, true, false},
{false, false, true, true, true, true, false, true, false, true, false, false, true, false, true, false, false, true},
{false, false, true, false, true, true, true, false, false, true, true, false, true, false, true, false, true, false},
{false, true, false, false, true, true, false, true, true, false, false, true, true, true, false, false, true, false},
{false, false, true, true, false, false, true, true, false, false, true, false, true, true, false, true, true, false},
{false, true, false, true, false, true, false, true, true, false, true, true, false, false, true, false, false, true},
{false, false, true, false, false, true, false, true, false, true, true, true, false, false, true, true, false, true},
{false, true, false, true, false, true, true, false, false, true, true, false, true, false, false, true, false, true},
{false, true, true, false, false, true, false, true, false, true, false, true, true, false, true, false, false, true},
{false, true, false, false, true, true, true, false, true, true, false, false, true, true, false, false, true, false},
{false, true, false, true, false, true, false, true, false, true, false, true, false, true, true, true, false, false},
{false, false, true, false, true, false, true, true, true, false, true, false, true, false, false, true, true, false},
{false, false, true, false, true, true, false, false, true, false, true, true, false, false, true, false, true, true},
{false, false, true, false, true, true, false, true, true, true, false, true, false, true, false, true, false, false},
{false, false, true, true, false, false, true, true, false, true, false, false, true, true, false, true, false, true},
{false, false, true, false, false, true, true, true, false, true, true, true, false, false, true, false, false, true},
{false, false, true, true, false, false, true, false, false, true, true, true, false, false, true, false, true, true},
{false, true, false, false, true, true, true, true, false, false, true, false, true, false, true, false, true, false},
{false, true, false, true, false, false, true, false, true, true, false, true, false, true, false, true, false, true},
{false, false, false, true, false, true, true, false, false, true, true, true, false, true, true, false, false, true}};

//This is an array of C-values which is used to determine a team's opponent during a given week.
int opponentarray12 [][18] = {{0, CSeahawks, CPatriots, CEagles, CDolphins, CRams, CBills, CVikings, CFortyNiners, CPackers, 0, CFalcons, CRams, CJets, CSeahawks, CLions, CBears, CFortyNiners},
{0, CChiefs, CBroncos, CChargers, CPanthers, CRedskins, CRaiders, 0, CEagles, CCowboys, CSaints, CCardinals, CBuccaneers, CSaints, CPanthers, CGiants, CLions, CBuccaneers},
{0, CBengals, CEagles, CPatriots, CBrowns, CChiefs, CCowboys, CTexans, 0, CBrowns, CRaiders, CSteelers, CChargers, CSteelers, CRedskins, CBroncos, CGiants, CBengals},
{0, CJets, CChiefs, CBrowns, CPatriots, CFortyNiners, CCardinals, CTitans, 0, CTexans, CPatriots, CDolphins, CColts, CJaguars, CRams, CSeahawks, CDolphins, CJets},
{0, CBuccaneers, CSaints, CGiants, CFalcons, CSeahawks, 0, CCowboys, CBears, CRedskins, CBroncos, CBuccaneers, CEagles, CChiefs, CChargers, CRaiders, CSaints},
{0, CColts, CPackers, CRams, CCowboys, CJaguars, 0, CLions, CPanthers, CTitans, CTexans, CFortyNiners, CVikings, CSeahawks, CVikings, CPackers, CCardinals, CLions},
{0, CRavens, CBrowns, CRedskins, CJaguars, CDolphins, CBrowns, CSteelers, 0, CBroncos, CGiants, CChiefs, CRaiders, CChargers, CCowboys, CEagles, CSteelers, CRavens},
{0, CEagles, CBengals, CBills, CRavens, CGiants, CBengals, CColts, CChargers, CRavens, 0, CCowboys, CSteelers, CRaiders, CChiefs, CRedskins, CBroncos, CSteelers},
{0, CGiants, CSeahawks, CBuccaneers, CBears, 0, CRavens, CPanthers, CGiants, CFalcons, CEagles, CBrowns, CRedskins, CEagles, CBengals, CSteelers, CSaints, CRedskins},
{0, CSteelers, CFalcons, CTexans, CRaiders, CPatriots, CChargers, 0, CSaints, CBengals, CPanthers, CChargers, CChiefs, CBuccaneers, CRaiders, CRavens, CBrowns, CChiefs},
{0, CRams, CFortyNiners, CTitans, CVikings, 0, CEagles, CBears, CSeahawks, CJaguars, CVikings, CPackers, CTexans, CColts, CPackers, CCardinals, CFalcons, CBears},
{0, CFortyNiners, CBears, CSeahawks, CSaints, CColts, CTexans, CRams, CJaguars, CCardinals, 0, CLions, CGiants, CVikings, CLions, CBears, CTitans, CVikings},
{0, CDolphins, CJaguars, CBroncos, CTitans, CJets, CPackers, CRavens, 0, CBills, CBears, CJaguars, CLions, CTitans, CPatriots, CColts, CVikings, CColts},
{0, CBears, CVikings, CJaguars, 0, CPackers, CJets, CBrowns, CTitans, CDolphins, CJaguars, CPatriots, CBills, CLions, CTitans, CTexans, CChiefs, CTexans},
{0, CVikings, CTexans, CColts, CBengals, CBears, 0, CRaiders, CPackers, CLions, CColts, CTexans, CTitans, CBills, CJets, CDolphins, CPatriots, CTitans},
{0, CFalcons, CBills, CSaints, CChargers, CRavens, CBuccaneers, 0, CRaiders, CChargers, CSteelers, CBengals, CBroncos, CPanthers, CBrowns, CRaiders, CColts, CBroncos},
{0, CTexans, CRaiders, CJets, CCardinals, CBengals, CRams, 0, CJets, CColts, CTitans, CBills, CSeahawks, CPatriots, CFortyNiners, CJaguars, CBills, CPatriots},
{0, CJaguars, CColts, CFortyNiners, CLions, CTitans, CRedskins, CCardinals, CBuccaneers, CSeahawks, CLions, 0, CBears, CPackers, CBears, CRams, CTexans, CPackers},
{0, CTitans, CCardinals, CRavens, CBills, CBroncos, CSeahawks, CJets, CRams, 0, CBills, CColts, CJets, CDolphins, CTexans, CFortyNiners, CJaguars, CDolphins},
{0, CRedskins, CPanthers, CChiefs, CPackers, CChargers, 0, CBuccaneers, CBroncos, CEagles, CFalcons, CRaiders, CFortyNiners, CFalcons, CGiants, CBuccaneers, CCowboys, CPanthers},
{0, CCowboys, CBuccaneers, CPanthers, CEagles, CBrowns, CFortyNiners, CRedskins, CCowboys, CSteelers, CBengals, 0, CPackers, CRedskins, CSaints, CFalcons, CRavens, CEagles},
{0, CBills, CSteelers, CDolphins, CFortyNiners, CTexans, CColts, CPatriots, CDolphins, 0, CSeahawks, CRams, CPatriots, CCardinals, CJaguars, CTitans, CChargers, CBills},
{0, CChargers, CDolphins, CSteelers, CBroncos, 0, CFalcons, CJaguars, CChiefs, CBuccaneers, CRavens, CSaints, CBengals, CBrowns, CBroncos, CChiefs, CPanthers, CChargers},
{0, CBrowns, CRavens, CCardinals, CGiants, CSteelers, CLions, 0, CFalcons, CSaints, CCowboys, CRedskins, CPanthers, CCowboys, CBuccaneers, CBengals, CRedskins, CGiants},
{0, CBroncos, CJets, CRaiders, 0, CEagles, CTitans, CBengals, CRedskins, CGiants, CChiefs, CRavens, CBrowns, CRavens, CChargers, CCowboys, CBengals, CBrowns},
{0, CLions, CRedskins, CBears, CSeahawks, CCardinals, CDolphins, CPackers, CPatriots, 0, CFortyNiners, CJets, CCardinals, CFortyNiners, CBills, CVikings, CBuccaneers, CSeahawks},
{0, CRaiders, CTitans, CFalcons, CChiefs, CSaints, CBroncos, 0, CBrowns, CChiefs, CBuccaneers, CBroncos, CRavens, CBengals, CSteelers, CPanthers, CJets, CRaiders},
{0, CPackers, CLions, CVikings, CJets, CBills, CGiants, CSeahawks, CCardinals, 0, CRams, CBears, CSaints, CRams, CDolphins, CPatriots, CSeahawks, CCardinals},
{0, CCardinals, CCowboys, CPackers, CRams, CPanthers, CPatriots, CFortyNiners, CLions, CVikings, CJets, 0, CDolphins, CBears, CCardinals, CBills, CFortyNiners, CRams},
{0, CPanthers, CGiants, CCowboys, CRedskins, 0, CChiefs, CSaints, CVikings, CRaiders, CChargers, CPanthers, CFalcons, CBroncos, CEagles, CSaints, CRams, CFalcons},
{0, CPatriots, CChargers, CLions, CTexans, CVikings, CSteelers, CBills, CColts, CBears, CDolphins, 0, CJaguars, CTexans, CColts, CJets, CPackers, CJaguars},
{0, CSaints, CRams, CBengals, CBuccaneers, CFalcons, CVikings, CGiants, CSteelers, CPanthers, 0, CEagles, CCowboys, CGiants, CRavens, CBrowns, CEagles, CCowboys}};
*/
